language: go
sudo: false
addons:
  postgresql: 9.4
go:
  - 1.11
  - 1.12
  - 1.13
  - 1.14
cache:
  directories:
  - samples
install:
  - go get -v 
  - ./download_samples.sh
script:
  - go install && ./test.sh
  - go test
